display_name: Mangayomi

package_name: mangayomi

maintainer:
  name: kodjodevf
  email: kodjomoustapha@gmail.com

priority: optional

section: x11

installed_size: 109400

depencencies:
  - libwebkit2gtk-4.1-0
  - libmpv2

essential: false

postinstall_scripts:
  - echo "Installed Mangayomi successfully"
  
postuninstall_scripts:
  - echo "Uninstalled Mangayomi successfully"
icon: assets/app_icons/icon-red.png

keywords:
  - Manga
  - Anime
  - BitTorrent

generic_name: Free and open source application that allows users to read manga and stream anime from a variety of sources including BitTorrent.

categories:
  - AudioVideo

startup_notify: true
